### ISSUE TITLE
Add a custom fundId field to uniquely identify funds

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/mutual-funds-manager#1]
While MongoDB generates a unique _id for each document, handling this long string for operations like updating or deleting a fund is impractical. To make it easier for users and developers, introduce a fundId that will be used in the API endpoints for managing individual funds. This fundId can either be a simple auto-incremented integer (e.g., 1, 2) or a short, human-readable unique string (e.g., fund1, fund2).

**Comment by BhavikaPradeep** [comment]
can i get assigned please

**Comment by Samyukta-b** [comment]
!assign @BhavikaPradeep 60

**Comment by Samyukta-b** [comment]
@BhavikaPradeep are you working on this repo??

**Comment by Samyukta-b** [comment]
!deassign

**Comment by sherlockhome12** [comment]
hey can i get this assigned??

**Comment by sherlockhome12** [comment]
@Samyukta-b

**Comment by Samyukta-b** [comment]
resolved by #13
