### ISSUE TITLE
Implement PUT API to update a fund

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/mutual-funds-manager#2]
We need to create a PUT API to allow users to update a specific mutual fund's data in the database. The API should accept the updated details in JSON format and update the fund using the fund's ID (#1) as a unique identifier. Finish #1 to start this.

Please update the README.md file accordingly with the endpoint, following the format already provided in the README.

**Comment by Rojas-Binny** [comment]
Could I please get assigned to this?

**Comment by Samyukta-b** [comment]
!assign @Rojas-Binny 60

**Comment by Rojas-Binny** [comment]
Can you give me some more time to work on this

**Comment by Rojas-Binny** [comment]
The update fund code has also been committed

**Comment by Samyukta-b** [comment]
!assign @Rojas-Binny 45

**Comment by Samyukta-b** [comment]
@Rojas-Binny are you currently working on this?

**Comment by Rojas-Binny** [comment]
I had committed the one for updating fund already, is it not working?

**Comment by Samyukta-b** [comment]
oh did you do it in the same one?

**Comment by Samyukta-b** [comment]
@Rojas-Binny can you let me know in which one you added it? the PR, please because i need to add bounty under that

**Comment by Rojas-Binny** [comment]
Yeah I accidentally pushed to the same one I think, could you check the PR, there should be 3 branches there

**Comment by Rojas-Binny** [comment]
@Samyukta-b, #13 is the one, could you please check this

**Comment by Samyukta-b** [comment]
i won't be able to give bounty point if you don't create a PR for it, just simply create a  empty one and i'll give

**Comment by Samyukta-b** [comment]
@Rojas-Binny

**Comment by Samyukta-b** [comment]
resolved by #13

**Comment by Rojas-Binny** [comment]
@Samyukta-b , Ok I shall raise an empty one right now
