### ISSUE TITLE
Implement DELETE API to remove a fund

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/mutual-funds-manager#3]
We need a DELETE API to remove a specific fund from the database. This API should take the fund ID (#1) as a parameter and remove it from the MongoDB collection. Finish #1 to start this.

Please update the README.md file accordingly with the endpoint, following the format already provided in the README.

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by Samyukta-b** [comment]
!assign @Git-Cat-21 60

**Comment by Git-Cat-21** [comment]
i am unable to work on it please deasign it

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Rojas-Binny** [comment]
Can I please get assigned to this?

**Comment by Samyukta-b** [comment]
!assign @Rojas-Binny 60

**Comment by Rojas-Binny** [comment]
Have raised a PR for this issue, please do look into it @Samyukta-b

**Comment by Samyukta-b** [comment]
yes i will look into it, i was taking abreak

**Comment by Rojas-Binny** [comment]
I have committed the code including the one for FundID, could you please look into it

**Comment by Samyukta-b** [comment]
resolved by #13
