### ISSUE TITLE
Create a User data structure

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/mutual-funds-manager#4]
We need to define a new User data structure to store user details, along with the mutual funds they have added. The user data should have fields like userID, username, email, any other field you think is appropriate and an array of Fund objects representing the mutual funds associated with that user.

**Comment by Advaith2805** [comment]
Can I get assigned to this

**Comment by Samyukta-b** [comment]
!assign @Advaith2805 60

**Comment by Samyukta-b** [comment]
this was resolved by #9

**Comment by Samyukta-b** [comment]
!deassign
