### ISSUE TITLE
Implement PUT API to update a user

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/mutual-funds-manager#5]
Create a PUT API to allow updation of user's details in the User database. The API should accept the updated details in JSON format and update the user details using the user ID as a unique identifier. Finish #4 to start this.

Please update the README.md file accordingly with the endpoint, following the format already provided in the README.

**Comment by Advaith2805** [comment]
Can I get assigned to this

**Comment by Advaith2805** [comment]
Can I get assigned to this

**Comment by Advaith2805** [comment]
Can I get assigned to this

**Comment by Samyukta-b** [comment]
#4 is being currently worked on, once that is complete you can be assigned to this. if nobody is working on it, you can request to work on that issue

**Comment by Samyukta-b** [comment]
!assign @Advaith2805 60

**Comment by Advaith2805** [comment]
Have I been assigned this

**Comment by Samyukta-b** [comment]
no would you liek to be?

**Comment by Advaith2805** [comment]
Yes

**Comment by Samyukta-b** [comment]
!assign @Advaith2805 60

**Comment by Samyukta-b** [comment]
@Advaith2805 i'm not getting any response from you, from any issue

**Comment by Advaith2805** [comment]
I cant see that I am assigned for this 
I would like to be

**Comment by Samyukta-b** [comment]
!assign @Advaith2805 60

**Comment by Advaith2805** [comment]
I still cant see that I am assigned

**Comment by Samyukta-b** [comment]
give me a mintue

**Comment by Samyukta-b** [comment]
!assign @Advaith2805 60

**Comment by Samyukta-b** [comment]
@Advaith2805 hi, hows it going? how is the progress, please update progress in the form of commits

**Comment by Advaith2805** [comment]
Yes am working on it will commit soon

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Samyukta-b** [comment]
!assign @Advaith2805 30

**Comment by Samyukta-b** [comment]
@Advaith2805 are you working on it? can you meet me in room 001

**Comment by Samyukta-b** [comment]
@Advaith2805 hello? what's the update regarding this?

**Comment by Lohithsurya** [comment]
!deassign

**Comment by Rojas-Binny** [comment]
Can I get assigned this?

**Comment by Samyukta-b** [comment]
!assign @Rojas-Binny 60

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Samyukta-b** [comment]
!assign @Rojas-Binny 60

**Comment by Samyukta-b** [comment]
the bot isn't working right now, but please go ahead working on this @Rojas-Binny

**Comment by Rojas-Binny** [comment]
I have sent a PR, please do take a look at it

**Comment by Samyukta-b** [comment]
resolved, i'll mention which issue later
