### ISSUE TITLE
Implement a DELETE API to delete a user

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/mutual-funds-manager#6]
Create a DELETE API to remove a specific user from the database. Finish #4 to start this.

Please update the README.md file accordingly with the endpoint, following the format already provided in the README.

**Comment by Advaith2805** [comment]
Can I get assigned to this

**Comment by Samyukta-b** [comment]
this issue cannot be complete without first finishing #4. if you would like to be assigned to that please comment under that

**Comment by Lohithsurya** [comment]
!assign @Advaith2805

**Comment by Advaith2805** [comment]
Have opened a pull request for the same

**Comment by Samyukta-b** [comment]
yes i am lokking into

**Comment by Advaith2805** [comment]
I have made a small correction to the earlier PR which is now working. Can I open a new PR for that

**Comment by Advaith2805** [comment]
Hello can I open a new PR

**Comment by Samyukta-b** [comment]
yes you can close the previous one

**Comment by Advaith2805** [comment]
Yes have closed the previous one and added a new one

**Comment by Samyukta-b** [comment]
resolved by #15

**Comment by Samyukta-b** [comment]
!deassign
