### ISSUE TITLE
Implement a GET API for user

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/mutual-funds-manager#7]
Create a GET api endpoint to get a specific user based on their userID along with their associated mutual funds. 

Finish #4 to start this.

Please update the README.md file accordingly with the endpoint, following the format already provided in the README.

**Comment by Rojas-Binny** [comment]
Can I get assigned to this

**Comment by Samyukta-b** [comment]
!assign @Rojas-Binny 60

**Comment by Rojas-Binny** [comment]
I have raised a PR for this, please do check @Samyukta-b

**Comment by Samyukta-b** [comment]
@Rojas-Binny yes give me some times I'm taking a break

**Comment by Samyukta-b** [comment]
!assign @Rojas-Binny 60

**Comment by Samyukta-b** [comment]
this was resolved by #11

**Comment by Samyukta-b** [comment]
!deassign
