### ISSUE TITLE
Implement a POST API for user

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/mutual-funds-manager#8]
Create a POST API to add new user data to the database. To ensure that your code is working, check that the user got added to mongoDB.

Finish #4 to start this.

Please update the README.md file accordingly with the endpoint, following the format already provided in the README.

**Comment by Advaith2805** [comment]
Can I get assigned to this

**Comment by Samyukta-b** [comment]
!assign @Advaith2805 60

**Comment by Samyukta-b** [comment]
@Advaith2805 are you assigned to soemthing else??

**Comment by Rojas-Binny** [comment]
Can I get assigned to this?

**Comment by Samyukta-b** [comment]
!assign @Rojas-Binny 60

**Comment by Rojas-Binny** [comment]
I have sent a PR for this issue @Samyukta-b, please do look into it

**Comment by Samyukta-b** [comment]
resolved by #12

**Comment by Samyukta-b** [comment]
!deassign
